# Upstream changes from _extends are only recognized when modifications are made to this file in the default branch.
_extends: .github
repository:
  name: aws-account-settings
  description: 'This component is responsible for provisioning account level settings: AWS Account Alias, EBS encryption, S3 block public access, alternate contacts, and SSM session preferences'
  homepage: https://cloudposse.com/accelerate
  topics: terraform, terraform-component









